### ISSUE TITLE
Code sharing: question

### ISSUE THREAD

**Issue by ahouben** [rob-derosa/Sport#1]
Hi @rob-derosa,

I have a question to your statement (google didn't give any obvious answer):

```
As of 11/11/2016, Sport features 93.6% code share (3.3% iOS / 3.1% Android).
```

How did you calculate those figures ? Any command line tools you can point me to ?

Thanks in advance,
alex

**Comment by rob-derosa** [comment]
Hi Alex,

If I remember correctly, the git CLI tool provides this purpose. Check out http://stackoverflow.com/questions/4822471/count-number-of-lines-in-a-git-repository

From there, I only considered code that was not auto-generated or boiler-plate code, and from .cs and .xaml files only.

Hope this helps,
Rob
